name: Release Nuget Packages on Nuget.org

on:
  push:
    tags:
    - "*"

jobs:
  release-nuget:
    runs-on: windows-latest
    env:
      GtkSharpVersion: 3.24.24.117-develop
      GtkSharpManifestVersion: 8.0.200
      DotnetVersion: 8.0.200
    steps:
      - name: Checkout MAUI repository
        uses: actions/checkout@v4
      
      - name: Setup .NET SDK ${{ env.DotnetVersion }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DotnetVersion }}

      - name: Install gtk workload
        run: |
            # For some reason automatic workload manifest detection doesn't work (see https://github.com/GtkSharp/GtkSharp/issues/355#issuecomment-1446262239), so download and uzip mainfest file manually
            dotnet nuget add source --name nuget.org "https://api.nuget.org/v3/index.json"
            C:\msys64\usr\bin\wget.exe https://www.nuget.org/api/v2/package/gtksharp.net.sdk.gtk.manifest-${{ env.GtkSharpManifestVersion }}/$GtkSharpVersion -O gtksharp.net.sdk.gtk.manifest-${{ env.GtkSharpManifestVersion }}.nupkg            
            set \a WORKLOAD_MANIFEST_DIR=C:\Program Files\dotnet\sdk-manifests\${{ env.DotnetVersion }}\gtksharp.net.sdk.gtk
            mkdir -p %WORKLOAD_MANIFEST_DIR%
            tar -xf -j gtksharp.net.sdk.gtk.manifest-${{ env.GtkSharpManifestVersion }}.nupkg "data/*" -C %WORKLOAD_MANIFEST_DIR%\
            rm gtksharp.net.sdk.gtk.manifest-${{ env.GtkSharpManifestVersion }}.nupkg
            icacls %WORKLOAD_MANIFEST_DIR%\* /grant Everyone:(F)
            dotnet workload search
            dotnet workload install gtk --skip-manifest-update

      - name: Get version information from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Pack
        run: |
            # sed -i 's/_IncludeAndroid>true/_IncludeAndroid>/g' Directory.Build.Override.props
            ./build.ps1 --target=dotnet-pack --configuration="Release" --verbosity=diagnostic --nugetsource="artifacts" -p:PackageVersion=${{ env.DotnetVersion }}-preview${{ github.sha }}

      - name: Push
        run: dotnet nuget push artifacts/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
