name: Pre-Release Nuget Packages on Nuget.org

on: [push, pull_request]

jobs:
  pre-release-nuget:
    runs-on: windows-latest
    env:
      GtkSharpVersion: 3.24.24.117-develop
      GtkSharpManifestVersion: 8.0.200
      DotnetVersion: 8.0.200
    steps:
      - name: Checkout MAUI repository
        uses: actions/checkout@v4
      
      - name: Setup .NET SDK ${{ env.DotnetVersion }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DotnetVersion }}

      - uses: msys2/setup-msys2@v2
      - name: Install gtk3
        shell: msys2 {0}
        run: |
            pacman -S mingw-w64-x86_64-gtk3 --noconfirm
            SETX /M PATH "%PATH%;C:\msys64\mingw64\bin"
            SETX /M PATH "%PATH%;C:\msys32\mingw32\bin"

      - name: Install gtk workload
        run: |
            # For some reason automatic workload manifest detection doesn't work (see https://github.com/GtkSharp/GtkSharp/issues/355#issuecomment-1446262239), so download and uzip mainfest file manually
            dotnet nuget add source --name nuget.org "https://api.nuget.org/v3/index.json"
            # C:\msys64\usr\bin\wget.exe https://www.nuget.org/api/v2/package/gtksharp.net.sdk.gtk.manifest-${{ env.GtkSharpManifestVersion }}/$Env:GtkSharpVersion -O gtksharp.net.sdk.gtk.manifest-${{ env.GtkSharpManifestVersion }}.nupkg            
            # $Env:WORKLOAD_MANIFEST_DIR = "C:\Program Files\dotnet\sdk-manifests\${{ env.DotnetVersion }}\gtksharp.net.sdk.gtk"
            # mkdir -p $Env:WORKLOAD_MANIFEST_DIR
            # tar -xf gtksharp.net.sdk.gtk.manifest-${{ env.GtkSharpManifestVersion }}.nupkg
            # cp data\* $Env:WORKLOAD_MANIFEST_DIR\
            # rm gtksharp.net.sdk.gtk.manifest-${{ env.GtkSharpManifestVersion }}.nupkg
            # icacls $Env:WORKLOAD_MANIFEST_DIR\* /grant Everyone:F
            # install gtk workload
            # git clone https://github.com/GtkSharp/GtkSharp.git
            # cd GtkSharp
            # dotnet tool restore
            # dotnet cake build.cake --BuildTarget=InstallWorkload
            # cp "C:\Program Files\dotnet\template-packs\*" "C:\Program Files\dotnet\templates\${{ env.DotnetVersion }}"
            # choco install msys2
            # refreshenv
            # pacman -Syu
            # pacman -S mingw-w64-x86_64-gtk3
            dotnet workload search
            dotnet workload install gtk --skip-manifest-update

      - name: Pack
        run: |
            # sed -i 's/_IncludeAndroid>true/_IncludeAndroid>/g' Directory.Build.Override.props
            ./build.ps1 --target=dotnet-pack --configuration="Release" --verbosity=diagnostic --nugetsource="artifacts" -p:PackageVersion=${{ env.DotnetVersion }}-preview${{ github.sha }}

      - name: Push
        run: dotnet nuget push artifacts/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
